### ISSUE TITLE
Allow copy the displayed text

### ISSUE THREAD

**Issue by bsussman** [Swivelgames/copy-find-results#2]
It would be nice for this to allow copying the buffer contents as displayed - e.g. 'all collapsed' or 'just the ones for which I want to have the details'.  Right now I have to drop to the command-line and grep for them.

Other than that, +1 for this plugin - it should be part of core.

**Comment by Swivelgames** [comment]
@bsussman Thanks for the suggestion!

Just to make sure I understand the request, you'd like to be able to collapse certain files in the search results in order to exclude them from the Copy buffer?

**Comment by bsussman** [comment]
Actually simpler - when I collapse all and copy the buffer, i want to exclude the collapsed details - it copies all those details - I just want to copy the list of files in which the matches were found (what is output from a grep -l)

**Comment by Swivelgames** [comment]
@bsussman Good idea! Working on it now.

**Comment by Swivelgames** [comment]
@bsussman Done! I added two settings. Let me know if these match what you're looking for. :)

![image](https://user-images.githubusercontent.com/1456302/45321677-99899b00-b50b-11e8-9337-19f08bffa247.png)

You'll probably find this one most useful: **Text Copy: Hide Results for Collapsed Files from Copy Buffer**.

**Comment by bsussman** [comment]
That works! Thanks. Job done.

(not an enhancement request) I am curious why a more intuitive highlight-copy-paste type action - I do not do atom development so I may not have my analysis straight but I imagine the standard editor folding could have been exploited. Though this might have required you to implement some language definition to allow you to identify what to fold. And highlight-copy-paste is fully supported in the editor :)

**Comment by Swivelgames** [comment]
@bsussman Agreed!

I had originally developed this because it did not fit within the scope of the built-in `find-and-replace` Atom Package. This originally contained supplemental functionality that some people found lacking in the original package. My hopes are that I'll continue to have time to expand on this and make it more user-friendly.

The current functionality of `find-and-replace` doesn't provide many features for copy/pasting results, unfortunately. However, this is on the roadmap for `copy-find-results`.

Any suggestions in the meantime are always welcome!
